# Generated by Django 3.1.2 on 2020-11-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropbox_link',
            name='description',
        ),
        migrations.AddField(
            model_name='dropbox_link',
            name='user',
            field=models.CharField(default='Jack', max_length=512),
        ),
        migrations.AlterField(
            model_name='dropbox_link',
            name='link',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
